/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SystemOverviewRouteImport } from './routes/system-overview'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as OfflineErrorRouteImport } from './routes/offline-error'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LecturerRouteImport } from './routes/lecturer'
import { Route as HelpRouteImport } from './routes/help'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DeviceSetupRouteImport } from './routes/device-setup'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LecturerSyncRouteImport } from './routes/lecturer.sync'
import { Route as LecturerLearnersRouteImport } from './routes/lecturer.learners'
import { Route as LecturerCoursesRouteImport } from './routes/lecturer.courses'
import { Route as LecturerBuilderRouteImport } from './routes/lecturer.builder'
import { Route as LecturerAssessmentsRouteImport } from './routes/lecturer.assessments'
import { Route as DashboardSyncRouteImport } from './routes/dashboard.sync'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardPlayerRouteImport } from './routes/dashboard.player'
import { Route as DashboardOfflineLibraryRouteImport } from './routes/dashboard.offline-library'
import { Route as DashboardMessagesRouteImport } from './routes/dashboard.messages'
import { Route as DashboardDownloadsRouteImport } from './routes/dashboard.downloads'
import { Route as DashboardCoursesRouteImport } from './routes/dashboard.courses'
import { Route as DashboardCertificatesRouteImport } from './routes/dashboard.certificates'
import { Route as DashboardAssignmentsRouteImport } from './routes/dashboard.assignments'
import { Route as DashboardAssessmentsRouteImport } from './routes/dashboard.assessments'
import { Route as CoreDeviceSyncRouteImport } from './routes/core.device-sync'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as AdminLocalServerRouteImport } from './routes/admin.local-server'
import { Route as AdminLecturersRouteImport } from './routes/admin.lecturers'
import { Route as AdminDevicesRouteImport } from './routes/admin.devices'
import { Route as AdminDepartmentsRouteImport } from './routes/admin.departments'
import { Route as AdminCoursesRouteImport } from './routes/admin.courses'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'

const SystemOverviewRoute = SystemOverviewRouteImport.update({
  id: '/system-overview',
  path: '/system-overview',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflineErrorRoute = OfflineErrorRouteImport.update({
  id: '/offline-error',
  path: '/offline-error',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LecturerRoute = LecturerRouteImport.update({
  id: '/lecturer',
  path: '/lecturer',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceSetupRoute = DeviceSetupRouteImport.update({
  id: '/device-setup',
  path: '/device-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LecturerSyncRoute = LecturerSyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => LecturerRoute,
} as any)
const LecturerLearnersRoute = LecturerLearnersRouteImport.update({
  id: '/learners',
  path: '/learners',
  getParentRoute: () => LecturerRoute,
} as any)
const LecturerCoursesRoute = LecturerCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => LecturerRoute,
} as any)
const LecturerBuilderRoute = LecturerBuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => LecturerRoute,
} as any)
const LecturerAssessmentsRoute = LecturerAssessmentsRouteImport.update({
  id: '/assessments',
  path: '/assessments',
  getParentRoute: () => LecturerRoute,
} as any)
const DashboardSyncRoute = DashboardSyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPlayerRoute = DashboardPlayerRouteImport.update({
  id: '/player',
  path: '/player',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOfflineLibraryRoute = DashboardOfflineLibraryRouteImport.update({
  id: '/offline-library',
  path: '/offline-library',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMessagesRoute = DashboardMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDownloadsRoute = DashboardDownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCoursesRoute = DashboardCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCertificatesRoute = DashboardCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAssignmentsRoute = DashboardAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAssessmentsRoute = DashboardAssessmentsRouteImport.update({
  id: '/assessments',
  path: '/assessments',
  getParentRoute: () => DashboardRoute,
} as any)
const CoreDeviceSyncRoute = CoreDeviceSyncRouteImport.update({
  id: '/core/device-sync',
  path: '/core/device-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLocalServerRoute = AdminLocalServerRouteImport.update({
  id: '/local-server',
  path: '/local-server',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLecturersRoute = AdminLecturersRouteImport.update({
  id: '/lecturers',
  path: '/lecturers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDevicesRoute = AdminDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDepartmentsRoute = AdminDepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/device-setup': typeof DeviceSetupRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/lecturer': typeof LecturerRouteWithChildren
  '/login': typeof LoginRoute
  '/offline-error': typeof OfflineErrorRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/system-overview': typeof SystemOverviewRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/devices': typeof AdminDevicesRoute
  '/admin/lecturers': typeof AdminLecturersRoute
  '/admin/local-server': typeof AdminLocalServerRoute
  '/admin/students': typeof AdminStudentsRoute
  '/core/device-sync': typeof CoreDeviceSyncRoute
  '/dashboard/assessments': typeof DashboardAssessmentsRoute
  '/dashboard/assignments': typeof DashboardAssignmentsRoute
  '/dashboard/certificates': typeof DashboardCertificatesRoute
  '/dashboard/courses': typeof DashboardCoursesRoute
  '/dashboard/downloads': typeof DashboardDownloadsRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/offline-library': typeof DashboardOfflineLibraryRoute
  '/dashboard/player': typeof DashboardPlayerRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/sync': typeof DashboardSyncRoute
  '/lecturer/assessments': typeof LecturerAssessmentsRoute
  '/lecturer/builder': typeof LecturerBuilderRoute
  '/lecturer/courses': typeof LecturerCoursesRoute
  '/lecturer/learners': typeof LecturerLearnersRoute
  '/lecturer/sync': typeof LecturerSyncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/device-setup': typeof DeviceSetupRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/lecturer': typeof LecturerRouteWithChildren
  '/login': typeof LoginRoute
  '/offline-error': typeof OfflineErrorRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/system-overview': typeof SystemOverviewRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/devices': typeof AdminDevicesRoute
  '/admin/lecturers': typeof AdminLecturersRoute
  '/admin/local-server': typeof AdminLocalServerRoute
  '/admin/students': typeof AdminStudentsRoute
  '/core/device-sync': typeof CoreDeviceSyncRoute
  '/dashboard/assessments': typeof DashboardAssessmentsRoute
  '/dashboard/assignments': typeof DashboardAssignmentsRoute
  '/dashboard/certificates': typeof DashboardCertificatesRoute
  '/dashboard/courses': typeof DashboardCoursesRoute
  '/dashboard/downloads': typeof DashboardDownloadsRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/offline-library': typeof DashboardOfflineLibraryRoute
  '/dashboard/player': typeof DashboardPlayerRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/sync': typeof DashboardSyncRoute
  '/lecturer/assessments': typeof LecturerAssessmentsRoute
  '/lecturer/builder': typeof LecturerBuilderRoute
  '/lecturer/courses': typeof LecturerCoursesRoute
  '/lecturer/learners': typeof LecturerLearnersRoute
  '/lecturer/sync': typeof LecturerSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/device-setup': typeof DeviceSetupRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/lecturer': typeof LecturerRouteWithChildren
  '/login': typeof LoginRoute
  '/offline-error': typeof OfflineErrorRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/system-overview': typeof SystemOverviewRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/devices': typeof AdminDevicesRoute
  '/admin/lecturers': typeof AdminLecturersRoute
  '/admin/local-server': typeof AdminLocalServerRoute
  '/admin/students': typeof AdminStudentsRoute
  '/core/device-sync': typeof CoreDeviceSyncRoute
  '/dashboard/assessments': typeof DashboardAssessmentsRoute
  '/dashboard/assignments': typeof DashboardAssignmentsRoute
  '/dashboard/certificates': typeof DashboardCertificatesRoute
  '/dashboard/courses': typeof DashboardCoursesRoute
  '/dashboard/downloads': typeof DashboardDownloadsRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/offline-library': typeof DashboardOfflineLibraryRoute
  '/dashboard/player': typeof DashboardPlayerRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/sync': typeof DashboardSyncRoute
  '/lecturer/assessments': typeof LecturerAssessmentsRoute
  '/lecturer/builder': typeof LecturerBuilderRoute
  '/lecturer/courses': typeof LecturerCoursesRoute
  '/lecturer/learners': typeof LecturerLearnersRoute
  '/lecturer/sync': typeof LecturerSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accessibility'
    | '/admin'
    | '/contact'
    | '/dashboard'
    | '/device-setup'
    | '/forgot-password'
    | '/help'
    | '/lecturer'
    | '/login'
    | '/offline-error'
    | '/onboarding'
    | '/register'
    | '/reset-password'
    | '/system-overview'
    | '/admin/analytics'
    | '/admin/courses'
    | '/admin/departments'
    | '/admin/devices'
    | '/admin/lecturers'
    | '/admin/local-server'
    | '/admin/students'
    | '/core/device-sync'
    | '/dashboard/assessments'
    | '/dashboard/assignments'
    | '/dashboard/certificates'
    | '/dashboard/courses'
    | '/dashboard/downloads'
    | '/dashboard/messages'
    | '/dashboard/offline-library'
    | '/dashboard/player'
    | '/dashboard/settings'
    | '/dashboard/sync'
    | '/lecturer/assessments'
    | '/lecturer/builder'
    | '/lecturer/courses'
    | '/lecturer/learners'
    | '/lecturer/sync'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accessibility'
    | '/admin'
    | '/contact'
    | '/dashboard'
    | '/device-setup'
    | '/forgot-password'
    | '/help'
    | '/lecturer'
    | '/login'
    | '/offline-error'
    | '/onboarding'
    | '/register'
    | '/reset-password'
    | '/system-overview'
    | '/admin/analytics'
    | '/admin/courses'
    | '/admin/departments'
    | '/admin/devices'
    | '/admin/lecturers'
    | '/admin/local-server'
    | '/admin/students'
    | '/core/device-sync'
    | '/dashboard/assessments'
    | '/dashboard/assignments'
    | '/dashboard/certificates'
    | '/dashboard/courses'
    | '/dashboard/downloads'
    | '/dashboard/messages'
    | '/dashboard/offline-library'
    | '/dashboard/player'
    | '/dashboard/settings'
    | '/dashboard/sync'
    | '/lecturer/assessments'
    | '/lecturer/builder'
    | '/lecturer/courses'
    | '/lecturer/learners'
    | '/lecturer/sync'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accessibility'
    | '/admin'
    | '/contact'
    | '/dashboard'
    | '/device-setup'
    | '/forgot-password'
    | '/help'
    | '/lecturer'
    | '/login'
    | '/offline-error'
    | '/onboarding'
    | '/register'
    | '/reset-password'
    | '/system-overview'
    | '/admin/analytics'
    | '/admin/courses'
    | '/admin/departments'
    | '/admin/devices'
    | '/admin/lecturers'
    | '/admin/local-server'
    | '/admin/students'
    | '/core/device-sync'
    | '/dashboard/assessments'
    | '/dashboard/assignments'
    | '/dashboard/certificates'
    | '/dashboard/courses'
    | '/dashboard/downloads'
    | '/dashboard/messages'
    | '/dashboard/offline-library'
    | '/dashboard/player'
    | '/dashboard/settings'
    | '/dashboard/sync'
    | '/lecturer/assessments'
    | '/lecturer/builder'
    | '/lecturer/courses'
    | '/lecturer/learners'
    | '/lecturer/sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccessibilityRoute: typeof AccessibilityRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DeviceSetupRoute: typeof DeviceSetupRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HelpRoute: typeof HelpRoute
  LecturerRoute: typeof LecturerRouteWithChildren
  LoginRoute: typeof LoginRoute
  OfflineErrorRoute: typeof OfflineErrorRoute
  OnboardingRoute: typeof OnboardingRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SystemOverviewRoute: typeof SystemOverviewRoute
  CoreDeviceSyncRoute: typeof CoreDeviceSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/system-overview': {
      id: '/system-overview'
      path: '/system-overview'
      fullPath: '/system-overview'
      preLoaderRoute: typeof SystemOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline-error': {
      id: '/offline-error'
      path: '/offline-error'
      fullPath: '/offline-error'
      preLoaderRoute: typeof OfflineErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecturer': {
      id: '/lecturer'
      path: '/lecturer'
      fullPath: '/lecturer'
      preLoaderRoute: typeof LecturerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device-setup': {
      id: '/device-setup'
      path: '/device-setup'
      fullPath: '/device-setup'
      preLoaderRoute: typeof DeviceSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecturer/sync': {
      id: '/lecturer/sync'
      path: '/sync'
      fullPath: '/lecturer/sync'
      preLoaderRoute: typeof LecturerSyncRouteImport
      parentRoute: typeof LecturerRoute
    }
    '/lecturer/learners': {
      id: '/lecturer/learners'
      path: '/learners'
      fullPath: '/lecturer/learners'
      preLoaderRoute: typeof LecturerLearnersRouteImport
      parentRoute: typeof LecturerRoute
    }
    '/lecturer/courses': {
      id: '/lecturer/courses'
      path: '/courses'
      fullPath: '/lecturer/courses'
      preLoaderRoute: typeof LecturerCoursesRouteImport
      parentRoute: typeof LecturerRoute
    }
    '/lecturer/builder': {
      id: '/lecturer/builder'
      path: '/builder'
      fullPath: '/lecturer/builder'
      preLoaderRoute: typeof LecturerBuilderRouteImport
      parentRoute: typeof LecturerRoute
    }
    '/lecturer/assessments': {
      id: '/lecturer/assessments'
      path: '/assessments'
      fullPath: '/lecturer/assessments'
      preLoaderRoute: typeof LecturerAssessmentsRouteImport
      parentRoute: typeof LecturerRoute
    }
    '/dashboard/sync': {
      id: '/dashboard/sync'
      path: '/sync'
      fullPath: '/dashboard/sync'
      preLoaderRoute: typeof DashboardSyncRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/player': {
      id: '/dashboard/player'
      path: '/player'
      fullPath: '/dashboard/player'
      preLoaderRoute: typeof DashboardPlayerRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/offline-library': {
      id: '/dashboard/offline-library'
      path: '/offline-library'
      fullPath: '/dashboard/offline-library'
      preLoaderRoute: typeof DashboardOfflineLibraryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/messages': {
      id: '/dashboard/messages'
      path: '/messages'
      fullPath: '/dashboard/messages'
      preLoaderRoute: typeof DashboardMessagesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/downloads': {
      id: '/dashboard/downloads'
      path: '/downloads'
      fullPath: '/dashboard/downloads'
      preLoaderRoute: typeof DashboardDownloadsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/courses': {
      id: '/dashboard/courses'
      path: '/courses'
      fullPath: '/dashboard/courses'
      preLoaderRoute: typeof DashboardCoursesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/certificates': {
      id: '/dashboard/certificates'
      path: '/certificates'
      fullPath: '/dashboard/certificates'
      preLoaderRoute: typeof DashboardCertificatesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/assignments': {
      id: '/dashboard/assignments'
      path: '/assignments'
      fullPath: '/dashboard/assignments'
      preLoaderRoute: typeof DashboardAssignmentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/assessments': {
      id: '/dashboard/assessments'
      path: '/assessments'
      fullPath: '/dashboard/assessments'
      preLoaderRoute: typeof DashboardAssessmentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/core/device-sync': {
      id: '/core/device-sync'
      path: '/core/device-sync'
      fullPath: '/core/device-sync'
      preLoaderRoute: typeof CoreDeviceSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/local-server': {
      id: '/admin/local-server'
      path: '/local-server'
      fullPath: '/admin/local-server'
      preLoaderRoute: typeof AdminLocalServerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lecturers': {
      id: '/admin/lecturers'
      path: '/lecturers'
      fullPath: '/admin/lecturers'
      preLoaderRoute: typeof AdminLecturersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/devices': {
      id: '/admin/devices'
      path: '/devices'
      fullPath: '/admin/devices'
      preLoaderRoute: typeof AdminDevicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/departments': {
      id: '/admin/departments'
      path: '/departments'
      fullPath: '/admin/departments'
      preLoaderRoute: typeof AdminDepartmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCoursesRoute: typeof AdminCoursesRoute
  AdminDepartmentsRoute: typeof AdminDepartmentsRoute
  AdminDevicesRoute: typeof AdminDevicesRoute
  AdminLecturersRoute: typeof AdminLecturersRoute
  AdminLocalServerRoute: typeof AdminLocalServerRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCoursesRoute: AdminCoursesRoute,
  AdminDepartmentsRoute: AdminDepartmentsRoute,
  AdminDevicesRoute: AdminDevicesRoute,
  AdminLecturersRoute: AdminLecturersRoute,
  AdminLocalServerRoute: AdminLocalServerRoute,
  AdminStudentsRoute: AdminStudentsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardRouteChildren {
  DashboardAssessmentsRoute: typeof DashboardAssessmentsRoute
  DashboardAssignmentsRoute: typeof DashboardAssignmentsRoute
  DashboardCertificatesRoute: typeof DashboardCertificatesRoute
  DashboardCoursesRoute: typeof DashboardCoursesRoute
  DashboardDownloadsRoute: typeof DashboardDownloadsRoute
  DashboardMessagesRoute: typeof DashboardMessagesRoute
  DashboardOfflineLibraryRoute: typeof DashboardOfflineLibraryRoute
  DashboardPlayerRoute: typeof DashboardPlayerRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSyncRoute: typeof DashboardSyncRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAssessmentsRoute: DashboardAssessmentsRoute,
  DashboardAssignmentsRoute: DashboardAssignmentsRoute,
  DashboardCertificatesRoute: DashboardCertificatesRoute,
  DashboardCoursesRoute: DashboardCoursesRoute,
  DashboardDownloadsRoute: DashboardDownloadsRoute,
  DashboardMessagesRoute: DashboardMessagesRoute,
  DashboardOfflineLibraryRoute: DashboardOfflineLibraryRoute,
  DashboardPlayerRoute: DashboardPlayerRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSyncRoute: DashboardSyncRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface LecturerRouteChildren {
  LecturerAssessmentsRoute: typeof LecturerAssessmentsRoute
  LecturerBuilderRoute: typeof LecturerBuilderRoute
  LecturerCoursesRoute: typeof LecturerCoursesRoute
  LecturerLearnersRoute: typeof LecturerLearnersRoute
  LecturerSyncRoute: typeof LecturerSyncRoute
}

const LecturerRouteChildren: LecturerRouteChildren = {
  LecturerAssessmentsRoute: LecturerAssessmentsRoute,
  LecturerBuilderRoute: LecturerBuilderRoute,
  LecturerCoursesRoute: LecturerCoursesRoute,
  LecturerLearnersRoute: LecturerLearnersRoute,
  LecturerSyncRoute: LecturerSyncRoute,
}

const LecturerRouteWithChildren = LecturerRoute._addFileChildren(
  LecturerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccessibilityRoute: AccessibilityRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DeviceSetupRoute: DeviceSetupRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HelpRoute: HelpRoute,
  LecturerRoute: LecturerRouteWithChildren,
  LoginRoute: LoginRoute,
  OfflineErrorRoute: OfflineErrorRoute,
  OnboardingRoute: OnboardingRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SystemOverviewRoute: SystemOverviewRoute,
  CoreDeviceSyncRoute: CoreDeviceSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
